name: Snyk Scan

# Trigger the workflow on push and pull request events to the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # 2. Log in to DockerHub  
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set up the Node.js environment with caching
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 4. Install dependencies with npm ci
      - name: Install dependencies
        run: npm ci

      # 5. Run Snyk SCA to check for vulnerabilities in my NPM dependencies
      - name: Run Snyk SCA scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high


      # 6. Run Snyk SAST to check for vulnerabilities in source code
      - name: Run Snyk SAST scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=high

      # 7. Pull the juiceshop image
      - name: Pull Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop

      # 8. Tag the image for DockerHub
      - name: Tag Docker Image
        run: docker tag bkimminich/juice-shop:latest ${{ secrets.DOCKER_USERNAME }}/juice-shop:latest

      # 9. Push the image to DockerHub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/juice-shop:latest

