name: Snyk Scan

# Trigger the workflow on push and pull request events to the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up the Node.js environment with caching
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3. Install dependencies with npm ci
      - name: Install dependencies
        run: npm ci